- type: replace
  path: /instance_groups/0/jobs/0:before
  value:
    release: registrar
    name: broker-registrar
    properties:
      cf:
        api: https://api.((system_domain))
        username: broker-registrar
        password: ((/((director_name))/cf/uaa_users_broker_registrar_password))
        skip_ssl_validation: ((skip_ssl_verify))
      brokers: []


- type: replace
  path: /releases/name=registrar?
  value:
    name: registrar
    version: "((registrar.version))"
    url: https://github.com/orange-cloudfoundry/registrar-boshrelease/releases/download/v((registrar.version))/registrar-((registrar.version)).tgz
