- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/scim/users/-
  value:
    name: broker-registrar
    password: "((uaa_users_broker_registrar_password))"
    groups:
    - cloud_controller.admin

- type: replace
  path: /variables/-
  value:
    name: uaa_users_broker_registrar_password
    type: password
